### ISSUE TITLE
[Bug]当只有3个或者3个以下个banner时，出现崩溃

### ISSUE THREAD

**Issue by merbng** [xfhy/EasyBanner#1]
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
![_20180331180637](https://user-images.githubusercontent.com/11256126/38162125-543d276a-350e-11e8-9d31-80e29b6da620.png)

**Comment by GuardYang** [comment]
你解决了？

**Comment by xfhy** [comment]
已解决,,哈哈,今天才看到.....
